spring:
  application:
    name: crud-app-backend
  datasource:
    url: jdbc:mysql://localhost:3306/crud_app_backend
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082